version: '3'
services:
  web:
    image: php:7.4-apache
    container_name: my-web-app
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=newsletter_db
  db:
    image: mysql:5.7
    container_name: my-mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=newsletter_db
